<?php

/***************************************************************
 * Extension Manager/Repository config file for ext: "migrate_samples"
 *
 * Auto generated by Extension Builder 21-02-14
 *
 * Manual updates:
 * Only the data in the array - anything else is removed by next write.
 * "version" and "dependencies" must not be touched!
 ***************************************************************/

$EM_CONF[$_EXTKEY] = array(
	'title' => 'Migrate samples',
	'description' => 'Migration samples for migrate extension',
	'category' => 'plugin',
	'author' => 'Helge Funk',
	'author_email' => 'helge.funk@e-net.info',
	'author_company' => '',
	'shy' => '',
	'priority' => '',
	'module' => '',
	'state' => 'alpha',
	'internal' => '',
	'uploadfolder' => '0',
	'createDirs' => '',
	'modify_tables' => '',
	'clearCacheOnLoad' => 0,
	'lockType' => '',
	'version' => '1.0.0-dev',
	'constraints' => array(
		'depends' => array(
			'extbase' => '6.2',
			'fluid' => '6.2',
			'typo3' => '6.2',
			'migrate' => '1.0',
		),
		'conflicts' => array(
		),
		'suggests' => array(
		),
	),
);

?>